version: '3.9'

services:
  bot:
    build: ./
    image: time_bot:1.0
    container_name: time_bot
    volumes:
      - ./configs/configs.json:/app/configs/configs.json
      - ./logs:/app/logs
    restart: unless-stopped
